name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} - {{ matrix.python }} - {{ matrix.bitness }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]
        python: [36, 37, 38, 39]
        bitness: [32, 64]
        exclude:
          - os: macos-latest
            bitness: 32

    steps:
      - uses: actions/checkout@v2

        # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.10.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014

          CIBW_BEFORE_ALL_LINUX: |
            if [[ ! -e $(command -v swig) ]]; then
            curl -L https://sourceforge.net/projects/swig/files/swig/swig-4.0.2/swig-4.0.2.tar.gz/download --output /tmp/swig.tar.gz
            mkdir /tmp/swig
            tar -xvzf /tmp/swig.tar.gz -C /tmp/swig --strip-components 1 &> /dev/null
            pushd /tmp/swig
            ./configure --without-alllang --with-python3 && make -j2 && make install > /dev/null
            popd
            fi
            pip install cmake ninja

          CIBW_BEFORE_ALL_WINDOWS: |
            choco install swig -f -y
            pip install cmake ninja

          CIBW_BEFORE_ALL_MACOS: |
            brew install swig
            pip install cmake ninja

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
